### ISSUE TITLE
Postal-app will not restart

### ISSUE THREAD

**Issue by JAP42** [ALinuxNinja/docker-postal#15]
I have found an issue while starting this on my new server. If I restart the postal-app container (Or it is forced to restart) the app will fail to start and then the container exits with an error code. The message in the log is `Error: Cannot be started in the foreground because supervisor already running`

**Comment by JAP42** [comment]
I added a stop command to the docker entrypoint file thinking it might clean out anything else that is still running. But now I see:

```
Error: Procodile supervisor isn't running


Error: Cannot be started in the foreground because supervisor already running

```

**Comment by JAP42** [comment]
Simple fix, this line in the entrypoint file needs a new path:

`rm -rf /opt/postal/tmp/pids/*`

New
`rm -rf /tmp/postal`

**Comment by eveandcats** [comment]
Fixed by your PR - thanks!
