### ISSUE TITLE
editing postal.yml

### ISSUE THREAD

**Issue by pjv** [ALinuxNinja/docker-postal#17]
Hi,

Am I supposed to be editing the postal.yml file somewhere at some time in the process of initially setting up docker-postal?

**Comment by eveandcats** [comment]
No, that is not needed

Docker automatically configures all the database details and credentials when starting up the container. You can add additional configuration by editing the jinja template at https://github.com/CatDeployed/docker-postal/blob/master/ubuntu/src/templates/postal.example.yml.j2 or from within the container at the `/templates/` path.
