### ISSUE TITLE
SMTP port not used

### ISSUE THREAD

**Issue by MadsRC** [ALinuxNinja/docker-postal#2]
Testing this container, I noticed that Postal starts listening on port 25, even though it's postal.yml contains smtp:port:2525.

I'm not sure if this is because postal.defaults.yml is overriding this ? Not sure either if it's a bug in this image or the Postal app.

**Comment by eveandcats** [comment]
Thanks for reporting, it's likely because of https://github.com/atech/postal/commit/d4fd6b99251da37f322b07f6a63724318a134170

I just have to do some testing for the web port, then I will update docker-compose to a correct version.

**Comment by eveandcats** [comment]
Right, there are two things that control SMTP - `smtp` and `smtp_server`. `smtp` indicates how postal is to access the server defined in `smtp_server`. As a result, the port in `smtp` indicates what port the SMTP server should be accessed on, not what port the SMTP server should listen on.

If you remove the old config, (data/postal) and let it be regenerated, it will now work.

**Comment by MadsRC** [comment]
Ah, I must have missed that.
Thank you very much!

On 10/05/17 13:33, StarryEyed wrote:
> Closed #2.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ALinuxNinja/docker-postal/issues/2#event-1077146944

-- 
Mads R. Havmand                                                 Systems Engineer
0x8CF81F51EFF2E0EE                                                    www.v42.dk
