### ISSUE TITLE
Worker process fails to start when app starts before rabbitmq

### ISSUE THREAD

**Issue by JAP42** [ALinuxNinja/docker-postal#20]
I have discovered an issue, my postal app container is dependent on rabbitmq container. However this only waits for container to start. No check for MQ to be ready. So the worker fails and re-spawning is disabled. So once rMQ is running I have to manually restart the postal app container. 

I can think of 2 possible solutions, 

1. enable re-spawning of the processes in Procdile
2. Add a health check for rabbitMQ in the docker-entrypoint file. 

I don't have much experience with ether service, but I would think re-spawning capability might have other benefits.

**Comment by eveandcats** [comment]
Added a fix.
