### ISSUE TITLE
Database re-initialized every time container is recreated

### ISSUE THREAD

**Issue by qodeboy** [ALinuxNinja/docker-postal#22]
In entrypoint we have check for existence of `postal.yml`. If it does not exists - database is reinitialized. The problem is that postal.yml is **not persistent**. 

Every time container is removed/recreated, the postal.yml is deleted forever. Thus, check will fail and database is reinitialized, even if it has **live data** in it.

Solution: either change check to check for actual database initialization (i.e. if tables are present), or use postal binary itself to check if it was initialized. Alternative is to persist generated `postal.yml` in `docker-compose.yml`.

**Comment by eveandcats** [comment]
Should be fixed now.
