### ISSUE TITLE
Bootstrapping Automation

### ISSUE THREAD

**Issue by saschaarthur** [ALinuxNinja/docker-postal#24]
Hello,

Awesome project so far, for something like this i was hoping for a long time !

The only thing im currently fighting with, is to get it even a bit more stateless.

Currently the database needs to be bootstrapped upfront (which is super easy if you dont include your custom config).

But if youre in a fresh environment (where db / rabbitmq is not initialized yet) postal fails to start because of missing tables/databases.

How to reproduce:
just clone the repo in a fresh env.
and include your own custom config: https://github.com/CatDeployed/docker-postal/blob/master/ubuntu/docker-compose.yml#L15

In this case the Bootstrap (create db / tables and seeds) is skipped.
Is there a way to force it / make it check if the tables are missing and bootstrap those?

Or do i always have to boostrap those tables manually upfront?
And then modify the docker-compose?

**Comment by eveandcats** [comment]
You should be able to use [these instructions](https://github.com/ILoveYaToo/docker-postal#using-the-postal-tool) to run the initialise the DB before running `docker-compose up`
