### ISSUE TITLE
Static assets

### ISSUE THREAD

**Issue by ianwalter** [ALinuxNinja/docker-postal#5]
Looks like the static assets aren't served and the Postal installation docs expect nginx to be set up to serve them. I can attempt a PR that adds a nginx service to the docker-compose if necessary.

**Comment by goldleon** [comment]
have the same issue here

**Comment by badjware** [comment]
This issue is also affecting me.  
@ianwalter I see that you started working on a fix, how close are you to be ready to submit a pr?  
I can also attempt to submit a pr

**Comment by ianwalter** [comment]
I got it working but not planning on submitting a PR. I'll create a separate project form the fork at some point but no ETA on that. Feel free to cherry pick the commit if you want.
