### ISSUE TITLE
fix wrapper.sh

### ISSUE THREAD

**Issue by mpochron** [ALinuxNinja/docker-postal#7]
```
sed -i -e'/main_db:/!b' -e ':a' -e "s/database.*/database: $MYSQL_DATABASE/;t trail" -e 'n;ba' -e ':trail' -e 'n;btrail' /opt/postal/config/postal.yml
```
variable from descritpion has been set, so I think it's a bug 

![image](https://user-images.githubusercontent.com/7736131/40880557-974727b4-66b3-11e8-8c22-34005ab95adf.png)

**Comment by eveandcats** [comment]
Fixed in latest version.
